-- USE mysql;
CREATE DATABASE DB_Rem;
-- CREATE USER 'Rem'@'localhost' IDENTIFIED BY '123';
-- GRANT ALL PRIVILEGES ON DB_Rem.* TO 'Rem';

GRANT ALL PRIVILEGES ON *.* TO 'Rem'@'%' IDENTIFIED BY '123' WITH GRANT OPTION;

FLUSH PRIVILEGES;