apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
          #env:
          #  - name: PMA_HOST
          #    value: mysql-service
          #  - name: PMA_PORT
          #    value: "3306"
            #- name: MYSQL_ROOT_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: mysql-secrets
            #      key: root-password